<a href="https://colab.research.google.com/github/OshankAgrawal/Foundation-of-Data-Science/blob/main/NUMPY_Library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**



*   NumPy is a Python library used for working with arrays.

* It also has functions for working in domain of linear algebra, fourier
transform, and matrices.

* NumPy stands for Numerical Python.



For more detail you can refer the link: https://www.geeksforgeeks.org/numpy-tutorial/

#Creating Array

**Create an Array by passing list or list of lists**

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([10, 20, 30], dtype=complex)
print(arr)

[10.+0.j 20.+0.j 30.+0.j]


**Crreate an array by passing a tupel into array()**

In [ ]:
tupel = ("Oshank","Agrawal")
array = np.array(tupel)
print(array)

['Oshank' 'Agrawal']


About **np.array()**

Reference Link: https://numpy.org/doc/stable/reference/generated/numpy.array.html

array() is used to create an array.


**Dimensions of array**

**Create a 0-D Array**

In [ ]:
array0s = np.array("Oshank")
print(array0s)

Oshank


In [ ]:
array0n = np.array(655)
print(array0n)

655


**Creating 1-D Array**

In [ ]:
array1n = np.array([1,2,3,4])
print(array1n)

[1 2 3 4]


In [ ]:
array1s = np.array(["Oshank","Agrawal","Artificial","Intelligence"])
print(array1s)

['Oshank' 'Agrawal' 'Artificial' 'Intelligence']


**Creating 2-d Array**

In [ ]:
array2n = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
array2s = np.array([["Oshank","A","Agrawal",],["Artificial","B","Intelligence"],["Data","C","Science"]])
print(array2s)

**Creating 3-D Array**

In [ ]:
array3n = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(array3n)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [ ]:
array3s = np.array([[["Oshank","A","Agrawal"],["Sakshi","B","Tiwari"],["Tanushree","C","Nayak"]],[["Harshraj","D","Ray"],["Shreyansh","E","Shukla"],["Suyash","F","Pawar"]],[["Madhavi","G"," "],["Palak","H","Dubey"],["Urvashi","I","Singh"]]])
print(array3s)

[[['Oshank' 'A' 'Agrawal']
  ['Sakshi' 'B' 'Tiwari']
  ['Tanushree' 'C' 'Nayak']]

 [['Harshraj' 'D' 'Ray']
  ['Shreyansh' 'E' 'Shukla']
  ['Suyash' 'F' 'Pawar']]

 [['Madhavi' 'G' ' ']
  ['Palak' 'H' 'Dubey']
  ['Urvashi' 'I' 'Singh']]]


#Array Dimension

**Check the dimensions of array**

In [ ]:
print(array0n.ndim)
print(array0s.ndim)
print(array1n.ndim)
print(array1s.ndim)
print(array2n.ndim)
print(array2s.ndim)
print(array3n.ndim)
print(array3s.ndim)

0
0
1
1
2
2
3
3


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr.ndim)

2


In [ ]:
tupel = ("Oshank","Agrawal")
array = np.array(tupel)
print(array.ndim)

1


**Higher Dimensional Array**

In [ ]:
arrayhd = np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=5)
print(arrayhd)
print("Number of dimensions; ",arrayhd.ndim)

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]
Number of dimensions;  5


#Access Array Element

**Access 1-D Array Element**

In [ ]:
print("Access the first element...",array1n[0])
print("Access the first element...",array1s[0])
print("Access the second element...",array1n[1])
print("Access the second element...",array1s[1])
print("Add the first & second element...",array1n[0]+array1n[1])
print("Add the first & second element...",array1s[0]+array1s[1])

Access the first element... 1
Access the first element... Oshank
Access the second element... 2
Access the second element... Agrawal
Add the first & second element... 3
Add the first & second element... OshankAgrawal


**Access 2-D Array Element**

In [ ]:
print("Middle element of the array...",array2s[1,1])

Middle element of the array... B


**Access 3-D Array Element**

In [ ]:
print("Middle element of the array...",array3s[1,1,1])

Middle element of the array... E


**Negative Indexing in 1-D array**

In [ ]:
print("Second last element of array....",array1n[-2])

Second last element of array.... 3


**Negative Indexing in 2-D Array**

In [ ]:
print("Second row first column",array2n[-2,-3])

4


#Iterations on Array

**Negative Indexing in 3-D Array**

In [ ]:
print(array3s[-1,-3,-3])

Madhavi


**Check the type of array**

In [ ]:
print(type(array0n))
print(type(array0s))
print(type(array1n))
print(type(array1s))
print(type(array2n))
print(type(array2s))
print(type(array3n))
print(type(array3s))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
tupel = ("Oshank","Agrawal")
array = np.array(tupel)
print(type(array))

<class 'numpy.ndarray'>


**Check the data type of elements of Array**

In [ ]:
print(array0n.dtype)
print(array0s.dtype)
print(array1n.dtype)
print(array1s.dtype)
print(array2n.dtype)
print(array2s.dtype)
print(array3n.dtype)
print(array3s.dtype)

int64
<U6
int64
<U12
int64
<U12
int64
<U9


In [ ]:
tupel = ("Oshank","Agrawal")
array = np.array(tupel)
print(array)
print(array.dtype)

['Oshank' 'Agrawal']
<U7


**Check the shape of array**

In [ ]:
print(array0n.shape)
print(array0s.shape)
print(array1n.shape)
print(array1s.shape)
print(array2n.shape)
print(array2s.shape)
print(array3n.shape)
print(array3s.shape)

()
()
(4,)
(4,)
(3, 3)
(3, 3)
(3, 3, 3)
(3, 3, 3)


In [ ]:
tupel = ("Oshank","Agrawal")
array = np.array(tupel)
print(array.shape)

(2,)


**Size of array**

In [ ]:
print(array0n.size)
print(array0s.size)
print(array1n.size)
print(array1s.size)
print(array2n.size)
print(array2s.size)
print(array3n.size)
print(array3s.size)

1
1
4
4
9
9
27
27


In [ ]:
tupel = ("Oshank","Agrawal")
array = np.array(tupel)
print(array.size)

2


---

#Slicing of Array

**Array Slicing**

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

**Slice the first row onward**

In [ ]:
print("Array before the slicing")
print(arr)
print ("\n")
print("Array after the slicing")
print(arr[1:4])

Array before the slicing
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Array after the slicing
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Slice all the items from the first column onward**

In [ ]:
print("Array before the slicing")
print(arr)
print ("\n")
print("Array after the slicing")
print(arr[0:4,1:3])

Array before the slicing
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Array after the slicing
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]


**Output should be second row only**

In [ ]:
print("Array before the slicing")
print(arr)
print ("\n")
print("Array after the slicing")
print(arr[1])

Array before the slicing
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Array after the slicing
[4 5 6]


**Output should be second column only**

In [ ]:
print("Array before the slicing")
print(arr)
print ("\n")
print("Array after the slicing")
print(arr[0:4,1:2])

Array before the slicing
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Array after the slicing
[[ 2]
 [ 5]
 [ 8]
 [11]]


In [ ]:
print("Array before the slicing")
print(arr)
print ("\n")
print("Array after the slicing")
print(arr[0:4,1])

Array before the slicing
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Array after the slicing
[ 2  5  8 11]
